spring:
  application:
    name: Notification-Service
  thymeleaf:
    cache: false
    mode: HTML
  mail:
    host: smtp.gmail.com
    port: 587
    username: "aniketpatil2268@gmail.com"
    password: "vscv oqfx urfx cdjf"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


